### ISSUE TITLE
Crashed When Install IMS APK

### ISSUE THREAD

**Issue by xjl12** [phhusson/treble_app#55]
Android 11, PixelExperience
Logs:
`07-22 16:39:44.184 19506 19506 E AndroidRuntime: FATAL EXCEPTION: main
07-22 16:39:44.184 19506 19506 E AndroidRuntime: Process: me.phh.treble.app, PID: 19506
07-22 16:39:44.184 19506 19506 E AndroidRuntime: java.lang.IllegalArgumentException: Can only download HTTP/HTTPS URIs: 
07-22 16:39:44.184 19506 19506 E AndroidRuntime: 	at android.app.DownloadManager$Request.<init>(DownloadManager.java:475)
07-22 16:39:44.184 19506 19506 E AndroidRuntime: 	at me.phh.treble.app.ImsSettingsFragment$onCreatePreferences$2.onPreferenceClick(ImsSettings.kt:107)
07-22 16:39:44.184 19506 19506 E AndroidRuntime: 	at androidx.preference.Preference.performClick(Preference.java:1184)
07-22 16:39:44.184 19506 19506 E AndroidRuntime: 	at androidx.preference.Preference.performClick(Preference.java:1166)
07-22 16:39:44.184 19506 19506 E AndroidRuntime: 	at androidx.preference.Preference$1.onClick(Preference.java:181)
07-22 16:39:44.184 19506 19506 E AndroidRuntime: 	at android.view.View.performClick(View.java:7455)
07-22 16:39:44.184 19506 19506 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:7432)
07-22 16:39:44.184 19506 19506 E AndroidRuntime: 	at android.view.View.access$3600(View.java:810)
07-22 16:39:44.184 19506 19506 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:28312)
07-22 16:39:44.184 19506 19506 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
07-22 16:39:44.184 19506 19506 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-22 16:39:44.184 19506 19506 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
07-22 16:39:44.184 19506 19506 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7664)
07-22 16:39:44.184 19506 19506 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-22 16:39:44.184 19506 19506 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
07-22 16:39:44.184 19506 19506 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
`

**Comment by phhusson** [comment]
what's the name of the "install ims" button?

Le jeu. 22 juil. 2021 à 10:45, Jale Shaw ***@***.***> a
écrit :

**Comment by xjl12** [comment]
![Screenshot_20210722-173821_PhhTrebleApp](https://user-images.githubusercontent.com/22131606/126619189-72af823e-3761-459a-ad46-b8850a515da1.png)
Maybe the app can't find the right url. My phone is MTK.

**Comment by phhusson** [comment]
I guess that's an Android 11 mediatek vendor?
I still haven't got any device to test it, or anyone willing to do the port

I'll have a device with mediatek Android 11 vendor in 2 months if noone
steps up with a solution until then

22 juil. 2021 11:40:31 Jale Shaw ***@***.***>:

[image: Screenshot_20210722-173821_PhhTrebleApp]
<https://user-images.githubusercontent.com/22131606/126619189-72af823e-3761-459a-ad46-b8850a515da1.png>
Maybe the app can't find the right url. My phone is MTK.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/phhusson/treble_app/issues/55#issuecomment-884782099>,
or unsubscribe

**Comment by xjl12** [comment]
Yes. My phone is Redmi 10X with Dimensity 820 (MT6873). If you need a test device, I could do that. Now I have flashed PixelExperience 11, there.are a hand of bugs in the GSI and I'm trying to fix them.

**Comment by skittels15** [comment]
For me same issue on Poco M3 Pro 5G/Redmi Note 10 5G. Devices has MTK Dimensity 700 (MT6833).
